### PR TITLE
Add Simplified Chinese Translation

### PR DESCRIPTION
**Pull request by samumist**
Thanks for this great content type. 
Added Simplified Chinese Translation.

### CODE REVIEW

**Comment by otacke** [comment]
@samumist You're welcome! Thanks for your contribution! I hope that the H5P core team will find some time to release an update of Image Juxtaposition soon that will include your transition.

**Comment by samumist** [comment]
@otacke 
Thanks for the heads up about the H5P core team release. No worries.

We've already using the latest release of your code within my team.

I'll send in another PR shortly with an identical translation but different Simplified Chinese variant, the `zh-hans.json`. 

I found the Simplified Chinese H5P translation landscape is crazy with different variant for different platform. 
Here's my findings:
截屏2022-02-16 14 10 23

Well, there's nothing we can do but provide all the variants for different platforms🤓

Thanks
Sam

**Comment by otacke** [comment]
@samumist I am not familiar with how H5P core decides what language to use. I'd assume the default would be to use a general version of a translation (e.g. de.json for standard German) if no specific variant is requested and to also use it as a fallback if a specific variant (e.g. de-ch.json for Swiss German) is requested by the platform but not provided by the content type, but I don't know if and how the H5P core team implemented that into H5P core/the integrations.

**Comment by samumist** [comment]
The fallback mechanism was not implemented in any of the platforms. When you switched to Simplified Chinese language, for example, on WordPress, the platform would look for the `zh` variant. If this particular variant is not present, it just shows the English language interface.

**Comment by otacke** [comment]
In that case, you should file-in a feature request for the H5P core team, I guess.

**Pull request merged**
